### ISSUE TITLE
ex210_pixels doesn't compile

### ISSUE THREAD

**Issue by hcorion** [Vladar4/sdl2_nim#12] opened 2017-11-23 01:33 UTC
Error I get is 
```
Hint: sdl_image [Processing]
/Users/hcorion/.nimble/pkgs/sdl2_nim-2.0.7.0/sdl2/sdl_image.nim(99, 20) template/generic instantiation from here
/Users/hcorion/.nimble/pkgs/sdl2_nim-2.0.7.0/sdl2/sdl_image.nim(43, 22) template/generic instantiation from here
/Users/hcorion/.nimble/pkgs/sdl2_nim-2.0.7.0/sdl2/private/version.nim(79, 27) Error: expression '2002' is of type 'int literal(2002)' and has to be discarded
    ((x) * 1000 + (y) * 100 + (z))
                            ^
```

This is on MacOS High Sierra 10.13.1
```
$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ nim --version
Nim Compiler Version 0.17.2 (2017-11-22) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 811fbdafd958443ddac98ad58c77245860b38620
active boot switches: -d:release -d:avoidTimeMachine -d:nativeStackTrace
```

I also tried with nim built from the latest git, same issue.

**Comment by wizzardx** [comment] 2017-11-23 06:23
Get the same here; on newest dev nim; running Debian.

I think the problem is on line 36 of sdl_image.nim

It's like this now:
```
template compiledVersion*() = ##  \
```

Compile seems to work if I change that line to this:

```
template compiledVersion*(): untyped = ##  \
```

**Comment by Vladar4** [comment] 2017-11-23 09:41
Have you updated sdl2_nim to latest [commit](https://github.com/Vladar4/sdl2_nim/commit/c1577bee3f7f612e6b9a3baa0dcca59038140a5e) though?

**Comment by hcorion** [comment] 2017-11-26 06:31
Ah, doing a `nimble install sdl2_nim@#head` fixed it, yes.

**Comment by Vladar4** [comment] 2017-11-26 11:26
Thanks for the feedback. Closing it for now then.

**Closed by Vladar4** 2017-11-26 11:26 UTC
